kind: Namespace
apiVersion: v1
metadata:
  name: {{.Values.namespace}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Values.namespace}}-service-mirror
  labels:
    ControllerComponentLabel: service-mirror
    ControllerNamespaceLabel: {{.Values.namespace}}
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints", "services", "secrets", "namespaces"]
  verbs: ["list", "get", "watch", "create", "delete", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Values.namespace}}-service-mirror
  labels:
    ControllerComponentLabel: service-mirror
    ControllerNamespaceLabel: {{.Values.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-{{.Values.namespace}}-service-mirror
subjects:
- kind: ServiceAccount
  name: linkerd-service-mirror
  namespace: {{.Values.namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-service-mirror
  namespace: {{.Values.namespace}}
  labels:
    ControllerComponentLabel: service-mirror
    ControllerNamespaceLabel: {{.Values.namespace}}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-service-mirror
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    ControllerComponentLabel: service-mirror
  ports:
  - name: grpc
    port: 8086
    targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ControllerComponentLabel: service-mirror
  name: linkerd-service-mirror
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      ControllerComponentLabel: service-mirror
      ControllerNamespaceLabel: {{.Values.namespace}}
  template:
    metadata:
      labels:
        ControllerComponentLabel: service-mirror
        ControllerNamespaceLabel: {{.Values.namespace}}
    spec:
      containers:
      - args:
        - service-mirror
        image: gcr.io/linkerd-io/controller:{{.Values.serviceMirrorVersion}}
        name: service-mirror
        ports:
        - containerPort: 8086
          name: grpc
        - containerPort: 9996
          name: admin-http
        securityContext:
          runAsUser: 2103
      serviceAccountName: linkerd-service-mirror
